version: '3.4'

services:
  directory.api:
    image: ${DOCKER_REGISTRY-}directoryapi
    build:
      context: .
      dockerfile: Directory.API/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04"
    environment:
            SA_PASSWORD: "qwertY12@3"
            ACCEPT_EULA: "Y"
    ports: 
            - "1433:1433"
    volumes:
            - sql_data_volume:/var/opt/mssql
volumes: 
    sql_data_volume: